//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOYEESAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPDETAIL
    {
        public int EMPLOYEEID { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> AGE { get; set; }
        public string SALARY { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string EMPROLE { get; set; }
    }
}
